#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:12.14
pipelines:
  default:
    - step:
        name: Deploying...
        #size: 2x
        caches:
          - node
        script: # Modify the commands below to build your repository.
         # - pipe: atlassian/slack-notify:0.3.6
          #  variables: 
           #   WEBHOOK_URL: 'https://hooks.slack.com/services/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'
            #  MESSAGE: 'Shop-Sasta Admin Deployment Started...'
          - npm install -g @angular/cli
          #- npm cache clean --force
          - apt-get update
          #- apt-get -qq install zip curl
          - ls && pwd
          - rm -rf node_modules
          - npm install
          - ls
          - ng build
          - ls -al
          - pipe: atlassian/rsync-deploy:0.4.4
            variables:
              USER: 'ubuntu'
              SERVER: 'www.ownimagetech.com'
              REMOTE_PATH: '/home/ubuntu/bit-cicd/athome-admin/'
              LOCAL_PATH: 'dist'
          #- zip -r dist.zip dist/*
          #- pipe: atlassian/sftp-deploy:0.5.6
          #  variables:
          #    USER: 'ubuntu'
          #    SERVER: '13.232.166.31'
          #    REMOTE_PATH: '/home/ubuntu/bit-cicd/'
          #    LOCAL_PATH: 'dist.zip'
              #SSH_KEY: $MY_SSH_KEY
              #PASSWORD: $PASSWORD
              DEBUG: 'true'      
          #- pipe: atlassian/ssh-run:0.2.6
          #  variables:
          #    SSH_USER: 'ubuntu'
          #    SSH_KEY: $MY_SSH_KEY
          #    SERVER: '13.232.166.31'
          #    COMMAND: 'sh /home/ubuntu/bit-cicd/scripts/run.sh'
              #MODE: 'script1'
              #COMMAND: './home/ubuntu/bit-cicd/scripts/build.sh'
          #- pipe: atlassian/slack-notify:0.3.6
          #  variables: 
          #    WEBHOOK_URL: 'https://hooks.slack.com/services/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'
          #    MESSAGE: 'Shop-Sasta Admin Deployed Successfully'
